//
// Created by nakos on 29-09-2026.
//

#ifndef TALLER1_ESTRUCTURAS_ARREGLODINAMICOTEMAS_H
#define TALLER1_ESTRUCTURAS_ARREGLODINAMICOTEMAS_H


class ArregloDinamicoTemas {
};


#endif //TALLER1_ESTRUCTURAS_ARREGLODINAMICOTEMAS_H
